In [2]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy

In [6]:
corpus = ["Machine learning is super fun",
"Python is super, super cool",
"Statistics is cool, too",
"Data science is fun",
"Python is great for machine learning",
"I like football",
"Football is great to watch"]

vectorizer = CountVectorizer(stop_words = 'english')

dtm = vectorizer.fit_transform(corpus)

pd.DataFrame(dtm.toarray(),index=corpus,columns=vectorizer.get_feature_names())

,cool,data,football,fun,great,learning,like,machine,python,science,statistics,super,watch
Machine learning is super fun,0,0,0,1,0,1,0,1,0,0,0,1,0
"Python is super, super cool",1,0,0,0,0,0,0,0,1,0,0,2,0
"Statistics is cool, too",1,0,0,0,0,0,0,0,0,0,1,0,0
Data science is fun,0,1,0,1,0,0,0,0,0,1,0,0,0
Python is great for machine learning,0,0,0,0,1,1,0,1,1,0,0,0,0
I like football,0,0,1,0,0,0,1,0,0,0,0,0,0
Football is great to watch,0,0,1,0,1,0,0,0,0,0,0,0,1

In [8]:
corpus = ["Machine learning is super fun",
"Python is super, super cool",
"Statistics is cool, too",
"Data science is fun",
"Python is great for machine learning",
"I like football",
"Football is great to watch"]
vectorizer = CountVectorizer(stop_words='english', ngram_range=(1,2), max_features=5)
dtm = vectorizer.fit_transform(corpus)
pd.DataFrame(dtm.toarray(),index=corpus,columns=vectorizer.get_feature_names()).head(5)

,cool,learning,machine learning,python,super
Machine learning is super fun,0,1,1,0,1
"Python is super, super cool",1,0,0,1,2
"Statistics is cool, too",1,0,0,0,0
Data science is fun,0,0,0,0,0
Python is great for machine learning,0,1,1,1,0